// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolyMyMarket.Context;

#nullable disable

namespace PolyMyMarket.Context.Migrations
{
    [DbContext(typeof(MarketContext))]
    partial class MarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolyMyMarket.Models.Market", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InitialLiquidity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NoPool")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ResolvedOutcome")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("YesPool")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cryptocurrency",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This market resolves to Yes if Bitcoin (BTC) reaches or exceeds $100,000 USD at any point before December 31, 2025 23:59:59 UTC. Otherwise resolves to No.",
                            EndDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            InitialLiquidity = 1000m,
                            NoPool = 500m,
                            Status = 0,
                            Title = "Will Bitcoin reach $100,000 by end of 2025?",
                            YesPool = 500m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technology",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This market resolves to Yes if a credible AI system is widely recognized as passing the Turing Test by December 31, 2025. The determination will be based on mainstream media and academic consensus.",
                            EndDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            InitialLiquidity = 1000m,
                            NoPool = 500m,
                            Status = 0,
                            Title = "Will AI pass the Turing Test in 2025?",
                            YesPool = 500m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Economics",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This market resolves to Yes if the United States enters a recession (defined as two consecutive quarters of negative GDP growth) at any point during 2025.",
                            EndDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            InitialLiquidity = 1000m,
                            NoPool = 500m,
                            Status = 0,
                            Title = "Will there be a recession in 2025?",
                            YesPool = 500m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Space",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This market resolves to Yes if SpaceX successfully lands human astronauts on the surface of Mars before December 31, 2030.",
                            EndDate = new DateTime(2030, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            InitialLiquidity = 1000m,
                            NoPool = 500m,
                            Status = 0,
                            Title = "Will SpaceX land humans on Mars by 2030?",
                            YesPool = 500m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Technology",
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "This market resolves to Yes if Google, IBM, Microsoft, or another major tech company announces a significant quantum computing breakthrough in 2025 that is covered by mainstream tech media.",
                            EndDate = new DateTime(2025, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            InitialLiquidity = 1000m,
                            NoPool = 500m,
                            Status = 0,
                            Title = "Will a major tech company announce a quantum computer breakthrough in 2025?",
                            YesPool = 500m
                        });
                });

            modelBuilder.Entity("PolyMyMarket.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PolyMyMarket.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AveragePriceNo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AveragePriceYes")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MarketId")
                        .HasColumnType("int");

                    b.Property<decimal>("NoShares")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalInvestedNo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalInvestedYes")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("YesShares")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId");

                    b.HasIndex("UserId", "MarketId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("PolyMyMarket.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 10000m,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@polymarket.com",
                            Name = "Demo User"
                        });
                });

            modelBuilder.Entity("PolyMyMarket.Models.Order", b =>
                {
                    b.HasOne("PolyMyMarket.Models.Market", "Market")
                        .WithMany("Orders")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolyMyMarket.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PolyMyMarket.Models.Position", b =>
                {
                    b.HasOne("PolyMyMarket.Models.Market", "Market")
                        .WithMany("Positions")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolyMyMarket.Models.User", "User")
                        .WithMany("Positions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Market");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PolyMyMarket.Models.Market", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("PolyMyMarket.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
